name: ci

on:
  push:
    branches:
      - 'main'
      
  pull_request:
    branches: 
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: 
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "djrneo" --password-stdin
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
